Repository bsideproject/palette-api-server, pull requests merged in 2022-08, with the labels that each got.

#16 [#8, #9, #10, #12, #13, #14, #15] jwt, login 기능 추가
  build.gradle
  src/main/java/com/palette/AppListener.java
  src/main/java/com/palette/BaseEntity.java
  src/main/java/com/palette/exception/SocialTypeNotFoundException.java
  src/main/java/com/palette/exception/TokenExpirationException.java
  src/main/java/com/palette/exception/TokenNotValidException.java
  src/main/java/com/palette/exception/common/BaseException.java
  src/main/java/com/palette/exception/common/ErrorType.java
  src/main/java/com/palette/infra/jwtTokenProvider/JwtAccessTokenInfo.java
  src/main/java/com/palette/infra/jwtTokenProvider/JwtRefreshTokenInfo.java
  src/main/java/com/palette/infra/jwtTokenProvider/JwtTokenInfo.java
  src/main/java/com/palette/infra/jwtTokenProvider/JwtTokenProvider.java
  src/main/java/com/palette/infra/jwtTokenProvider/JwtTokenType.java
  src/main/java/com/palette/token/domain/RefreshToken.java
  src/main/java/com/palette/token/repository/RefreshTokenRepository.java
  src/main/java/com/palette/user/UserController.java
  src/main/java/com/palette/user/domain/SocialType.java
  src/main/java/com/palette/user/domain/User.java
  src/main/java/com/palette/user/dto/LoginRequest.java
  src/main/java/com/palette/user/dto/TokenResponse.java
  src/main/java/com/palette/user/repository/UserRepository.java
  src/main/java/com/palette/user/service/UserService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 기능

#21 Chore: dev.yml DB 정보 수정 및 jpa, logback 설정
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 설정

#23 Chore: dev.yml open-in-view true로 변경
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 설정

#24 Chore: dev.yml mysql 정보 컨테이너 이름으로 변경
  src/main/resources/application-dev.yml
Labels: 설정

#27 [#25, #26, #28] 토큰 갱신 기능 추가
  .gitignore
  server/logs/api.log
  src/main/java/com/palette/BaseEntity.java
  src/main/java/com/palette/user/UserController.java
  src/main/java/com/palette/user/service/UserService.java
Labels: 기능, 리팩토링, 설정

#29 Feat: 일기 등록 API
  build.gradle
  server/logs/api.log
  src/main/java/com/palette/BaseEntity.java
  src/main/java/com/palette/PaletteApplication.java
  src/main/java/com/palette/diary/domain/Diary.java
  src/main/java/com/palette/diary/domain/DiaryGroup.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/fetcher/dto/CreateDiaryInput.java
  src/main/java/com/palette/diary/fetcher/dto/CreateDiaryOutput.java
  src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
  src/main/java/com/palette/diary/repository/DiaryRepository.java
  src/main/resources/application-local.yml
  src/main/resources/schema/diary.graphqls
Labels: 기능

#36 Fix: @DgsQuery field 속성 사용해서 메소드명 자바 컨벤션으로 변경
  src/main/java/com/palette/color/fetcher/ColorFetcher.java
Labels: 리팩토링

#35 Feat: myProfile query
  build.gradle
  src/main/java/com/palette/diary/fetcher/dto/CreateDiaryInput.java
  src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
  src/main/java/com/palette/diary/repository/DiaryRepository.java
  src/main/java/com/palette/user/UserController.java
  src/main/java/com/palette/user/domain/User.java
  src/main/java/com/palette/user/fetcher/UserFetcher.java
  src/main/java/com/palette/user/fetcher/dto/LoginRequest.java
  src/main/java/com/palette/user/fetcher/dto/TokenResponse.java
  src/main/java/com/palette/user/service/UserService.java
  src/main/resources/schema/color.graphqls
  src/main/resources/schema/common.graphql
  src/main/resources/schema/diary.graphqls
  src/main/resources/schema/user.graphql
Labels: 기능

#33 Feat: 초대코드를 통한 일기그룹 유저 초대 (#31)
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/fetcher/dto/CreateDiaryOutput.java
  src/main/java/com/palette/diary/fetcher/dto/InviteDiaryInput.java
  src/main/java/com/palette/diary/fetcher/dto/InviteDiaryOutput.java
  src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
  src/main/java/com/palette/diary/repository/DiaryRepository.java
  src/main/resources/schema/diary.graphqls
Labels: 기능

#42 [#39] feat: file upload, delete api 추가
  .DS_Store
  build.gradle
  src/main/java/com/palette/file/FileController.java
  src/main/java/com/palette/file/FileService.java
  src/main/java/com/palette/file/dto/UploadResponse.java
  src/main/java/com/palette/infra/s3/S3Client.java
Labels: 기능

#51 Fix: 색깔 그라데이션 효과에 따른 startCode, endCode 엔티티, response 추가 (#50)
  src/main/java/com/palette/color/domain/Color.java
  src/main/java/com/palette/color/fetcher/ColorFetcher.java
  src/main/java/com/palette/color/fetcher/dto/ReadColorOutput.java
  src/main/resources/schema/color.graphqls
Labels: 수정

#55 Refactor: diary 엔티티, color 엔티티 @ManyToOne 설정으로 인한 리펙토링
  src/main/java/com/palette/color/fetcher/ColorFetcher.java
  src/main/java/com/palette/color/fetcher/dto/ReadColorOutput.java
  src/main/java/com/palette/diary/domain/Diary.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/fetcher/dto/CreateDiaryInput.java
  src/main/resources/schema/color.graphqls
  src/main/resources/schema/diary.graphqls
Labels: 리팩토링

#53 Fix: 초대코드 API 토큰값 파싱 로직 및 graphql 수정 (#52)
  src/main/java/com/palette/diary/domain/DiaryGroup.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/fetcher/dto/InviteDiaryOutput.java
  src/main/resources/schema/diary.graphqls
Labels: 수정

#49 Feat: Graphql & Rest 글로벌 예외처리 (#40)
  src/main/java/com/palette/exception/GraphqlExceptionHandler.java
  src/main/java/com/palette/exception/RestExceptionHandler.java
  src/main/java/com/palette/exception/SocialTypeNotFoundException.java
  src/main/java/com/palette/exception/TokenExpirationException.java
  src/main/java/com/palette/exception/TokenNotValidException.java
  src/main/java/com/palette/exception/common/BaseException.java
  src/main/java/com/palette/exception/common/ErrorType.java
  src/main/java/com/palette/exception/common/ExceptionResponse.java
  src/main/java/com/palette/exception/common/GlobalErrorType.java
  src/main/java/com/palette/exception/common/GraphqlException.java
  src/main/java/com/palette/exception/common/RestException.java
  src/main/java/com/palette/exception/graphql/DummyException.java
  src/main/java/com/palette/exception/rest/SocialTypeNotFoundException.java
  src/main/java/com/palette/exception/rest/TokenExpirationException.java
  src/main/java/com/palette/exception/rest/TokenNotValidException.java
  src/main/java/com/palette/infra/jwtTokenProvider/JwtTokenProvider.java
  src/main/java/com/palette/user/domain/SocialType.java
  src/main/java/com/palette/user/service/UserService.java
  src/main/resources/application.yml
Labels: 기능

#59 Refactor: 스키마 파일 구조 변경 (#56)
  src/main/java/com/palette/color/fetcher/ColorFetcher.java
  src/main/java/com/palette/color/fetcher/dto/ReadColorOutput.java
  src/main/resources/schema/color.graphqls
  src/main/resources/schema/common.graphql
  src/main/resources/schema/diary.graphqls
  src/main/resources/schema/entity.graphql
  src/main/resources/schema/user.graphql
Labels: 리팩토링

#62 Fix: 일기장 히스토리 생성시 기간 선택 graphqls input, output field명 변경 (#57)
  src/main/resources/schema/diary.graphqls
Labels: 수정

#66 Fix/files upload
  src/main/java/com/palette/file/FileController.java
  src/main/java/com/palette/file/FileService.java
  src/main/java/com/palette/file/dto/UploadResponse.java
Labels: 수정

#65 Fix/login api
  src/main/java/com/palette/user/UserController.java
  src/main/java/com/palette/user/domain/User.java
  src/main/java/com/palette/user/fetcher/UserFetcher.java
  src/main/java/com/palette/user/fetcher/dto/EditMyProfileInput.java
  src/main/java/com/palette/user/fetcher/dto/LoginResponse.java
  src/main/java/com/palette/user/service/UserService.java
  src/main/resources/schema/entity.graphql
  src/main/resources/schema/user.graphql
Labels: 수정

#67 Feat: 홈화면 일기장 전체 조회 (#41)
  build.gradle
  src/main/java/com/palette/config/QueryDslConfig.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
  src/main/java/com/palette/diary/repository/DiaryRepository.java
  src/main/java/com/palette/diary/repository/HistoryRepository.java
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
  src/main/resources/schema/diary.graphqls
  src/main/resources/schema/entity.graphql
Labels: 기능

#68 Fix: data jpa isAdmin 타입 변경(integer -> boolean)
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
Labels: 버그

#70 Feat/fcm test
  src/main/java/com/palette/infra/fcm/FcmService.java
  src/main/java/com/palette/user/domain/User.java
  src/main/java/com/palette/user/fetcher/UserFetcher.java
  src/main/java/com/palette/user/fetcher/dto/EditMyProfileInput.java
  src/main/java/com/palette/user/fetcher/dto/SendTestNotificationInput.java
  src/main/resources/schema/entity.graphql
  src/main/resources/schema/user.graphql
Labels: 기능

#69 Feat/page
  src/main/java/com/palette/diary/domain/Page.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/fetcher/dto/CreatePageInput.java
  src/main/java/com/palette/diary/fetcher/dto/PageQueryInput.java
  src/main/java/com/palette/diary/repository/PageRepository.java
  src/main/java/com/palette/user/domain/User.java
  src/main/resources/schema/diary.graphqls
  src/main/resources/schema/entity.graphql
Labels: 기능

#71 Feat: 일기관련 API 예외처리
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
  src/main/java/com/palette/diary/repository/HistoryRepository.java
  src/main/java/com/palette/exception/common/GlobalErrorType.java
  src/main/java/com/palette/exception/graphql/ColorNotFoundException.java
  src/main/java/com/palette/exception/graphql/DiaryExistUserException.java
  src/main/java/com/palette/exception/graphql/DiaryNotFoundException.java
  src/main/java/com/palette/exception/graphql/DiaryOutedUserException.java
  src/main/java/com/palette/exception/graphql/DiaryOverUserException.java
  src/main/java/com/palette/exception/graphql/InviteCodeNotFoundException.java
  src/main/java/com/palette/exception/graphql/ProgressedHistoryException.java
  src/main/java/com/palette/exception/graphql/UserNotFoundException.java
Labels: 기능

#73 fix: userId added in tokens
  src/main/java/com/palette/infra/jwtTokenProvider/JwtTokenProvider.java
  src/main/java/com/palette/user/UserController.java
  src/main/java/com/palette/user/service/UserService.java
Labels: 수정

#75 Feat: 일기 리스트 및 최근 페이지 조회 (#41), Chore: p6spy 추가 (#72)
  src/main/java/com/palette/BaseEntity.java
  src/main/java/com/palette/aop/LoginUserAspect.java
  src/main/java/com/palette/common/P6spyConfig.java
  src/main/java/com/palette/common/P6spyPrettySqlFormatter.java
  src/main/java/com/palette/diary/domain/History.java
  src/main/java/com/palette/diary/domain/Page.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/fetcher/dto/CreateHistoryInput.java
  src/main/java/com/palette/diary/repository/PageRepository.java
  src/main/java/com/palette/exception/RestExceptionHandler.java
  src/main/java/com/palette/infra/jwtTokenProvider/JwtTokenProvider.java
  src/main/java/com/palette/resolver/LoginUser.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/schema/entity.graphql
Labels: 기능, 설정, 수정

#81 Fix: LocalDateTime 반환을 위한 라이브러리 추가 (#80)
  build.gradle
  src/main/java/com/palette/BaseEntity.java
  src/main/java/com/palette/token/domain/RefreshToken.java
  src/main/resources/schema/entity.graphql
Labels: 버그

#82 Feat: 일기장 나가기 (#78)
  src/main/java/com/palette/diary/domain/DiaryGroup.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/fetcher/dto/OutDiaryInput.java
  src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
  src/main/resources/schema/diary.graphqls
Labels: 기능

#83 Feat: 일기장 이름 수정 & 일기장 커버 색상 변경 (#77)
  src/main/java/com/palette/diary/domain/Diary.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/fetcher/dto/UpdateDiaryInput.java
  src/main/resources/schema/diary.graphqls
Labels: 기능
