Repository bsideproject/palette-api-server, pull requests merged in 2022-09, with the labels that each got.

#85 Fix: 일기 최근 글 조회시 3개 제한 및 생성일자 내림차순
  src/main/java/com/palette/common/BaseRepository.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
Labels: 수정

#87 Fix: Page.author 중복 제거
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
Labels: 버그

#91 Feat: 프로메테우스, actuator 설정
  build.gradle
  src/main/resources/application.yml
Labels: 설정

#92 Feat: 프로메테우스, actuator 설정 추가
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 설정

#93 Chore: 로그백 xml 설정으로 변경
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: 설정

#94 Chore: 로그백 xml 설정 수정
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: 설정

#90 Feat: 센트리 설정
  build.gradle
  src/main/java/com/palette/common/S3Properties.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/exception/GraphqlExceptionHandler.java
  src/main/java/com/palette/exception/RestExceptionHandler.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 설정

#88 Feat/scheduler
  build.gradle
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/DiaryRepository.java
  src/main/java/com/palette/diary/service/DiaryService.java
  src/main/java/com/palette/infra/fcm/FcmService.java
  src/main/java/com/palette/infra/fcm/PushNotificationService.java
  src/main/java/com/palette/infra/scheduler/AutowiringSpringBeanJobFactory.java
  src/main/java/com/palette/infra/scheduler/SchedulerConfig.java
  src/main/java/com/palette/infra/scheduler/job/HistoryFinished.java
  src/main/java/com/palette/user/repository/UserRepository.java
  src/main/resources/quartz.properties
Labels: 기능

#99 Fix: 수정
  src/main/java/com/palette/aop/LoginUserAspect.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/fetcher/dto/InviteDiaryInput.java
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
  src/main/resources/schema/diary.graphqls
Labels: 수정

#101 Fix: 일기 수정
  src/main/java/com/palette/common/PageInput.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/PageRepository.java
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
  src/main/resources/schema/diary.graphqls
Labels: 수정

#102 Fix:
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/exception/common/GlobalErrorType.java
  src/main/java/com/palette/exception/graphql/HistoryNotFoundException.java
  src/main/java/com/palette/file/FileController.java
  src/main/java/com/palette/file/FileService.java
  src/main/java/com/palette/infra/fcm/PushNotificationService.java
  src/main/java/com/palette/user/fetcher/UserFetcher.java
Labels: 버그, 수정

#104 Fix: 현재 진행중인 history 쿼리 변경
  src/main/java/com/palette/diary/domain/History.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/HistoryRepository.java
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
Labels: 설정

#107 Feature/alarm history
  src/main/java/com/palette/alarm/domain/AlarmHistory.java
  src/main/java/com/palette/alarm/repository/AlarmHistoryRepository.java
  src/main/java/com/palette/alarm/service/AlarmHistoryService.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/infra/fcm/PushNotificationService.java
Labels: 기능, 수정

#108 Feat: 알림 히스토리 조회 및 수정
  src/main/java/com/palette/alarmhistory/domain/AlarmHistory.java
  src/main/java/com/palette/alarmhistory/fetcher/AlarmHistoryFetcher.java
  src/main/java/com/palette/alarmhistory/repository/AlarmHistoryQueryRepository.java
  src/main/java/com/palette/alarmhistory/repository/AlarmHistoryRepository.java
  src/main/java/com/palette/alarmhistory/service/AlarmHistoryService.java
  src/main/java/com/palette/exception/common/GlobalErrorType.java
  src/main/java/com/palette/exception/graphql/AlarmHistoryNotFoundException.java
  src/main/java/com/palette/infra/fcm/PushNotificationService.java
  src/main/resources/schema/alarmhistory.graphql
  src/main/resources/schema/entity.graphql
Labels: 기능

#113 Chore: 유레카 클라이언트 추가
  build.gradle
  src/main/java/com/palette/PaletteApplication.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 설정

#116 Refactor: 히스토리 홈 조회 N+1 해결
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/PageRepository.java
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
Labels: 리팩토링

#117 Fix: 알림 데이터에 alarmHistoryId 추가
  src/main/java/com/palette/alarmhistory/service/AlarmHistoryService.java
  src/main/java/com/palette/infra/fcm/PushNotificationService.java
Labels: 수정

#118 Fix: 알림 데이터에 alarmHistoryId 추가
  src/main/java/com/palette/infra/fcm/PushNotificationService.java
Labels: 수정

#119 Fix: 알림 읽음처리 mutation 요청값 배열로 변경
  src/main/java/com/palette/alarmhistory/fetcher/AlarmHistoryFetcher.java
  src/main/java/com/palette/alarmhistory/repository/AlarmHistoryRepository.java
  src/main/resources/schema/alarmhistory.graphql
Labels: 수정

#120 Fix: 알림 읽음처리 mutation 요청값 배열로 변경
  src/main/java/com/palette/alarmhistory/fetcher/dto/ReadAlarmHistoriesInput.java
Labels: 수정

#121 Refactor: Push Notification 비동기 변경 (#95)
  src/main/java/com/palette/config/EventsConfig.java
  src/main/java/com/palette/config/SpringAsyncConfig.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/event/Event.java
  src/main/java/com/palette/event/Events.java
  src/main/java/com/palette/event/EventsKind.java
  src/main/java/com/palette/event/PushAlarmEvent.java
  src/main/java/com/palette/event/PushAlarmEventDto.java
  src/main/java/com/palette/event/PushAlarmEventHandler.java
  src/main/java/com/palette/infra/fcm/PushNotificationService.java
  src/main/java/com/palette/infra/scheduler/job/HistoryFinished.java
Labels: 리팩토링

#122 Fix: diaryGroup 조회시 fetchJoin으로 user,diary 조회
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
  src/main/java/com/palette/event/PushAlarmEventDto.java
  src/main/java/com/palette/infra/fcm/PushNotificationService.java
Labels: 버그

#123 Fix: 일기초대 알림 버그픽스
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/event/PushAlarmEventDto.java
  src/main/java/com/palette/event/PushAlarmEventHandler.java
  src/main/java/com/palette/infra/fcm/FcmService.java
  src/main/java/com/palette/infra/fcm/PushNotificationService.java
  src/main/java/com/palette/user/repository/UserRepository.java
Labels: 수정

#124 Fix: 일기 조회 N + 1 일부 해결
  src/main/java/com/palette/diary/DiaryFetcherDto.java
  src/main/java/com/palette/diary/dataloader/CurrentHistoryDataLoader.java
  src/main/java/com/palette/diary/dataloader/JoinUserDataLoader.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
  src/main/resources/schema/diary.graphqls
Labels: 리팩토링

#125 Fix: 코드정리
  src/main/java/com/palette/diary/dataloader/CurrentHistoryDataLoader.java
  src/main/java/com/palette/diary/dataloader/JoinUserDataLoader.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/service/DiaryService.java
  src/main/resources/schema/diary.graphqls
Labels: 리팩토링

#126 Fix: 일기, 히스토리 조회시 page 페이징 값 전달 수정
  src/main/java/com/palette/diary/DiaryFetcherDto.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
Labels: 버그

#127 Fix: 일기 조회시 currentHistory, diaryStatus 매칭 버그픽스
  src/main/java/com/palette/diary/dataloader/CurrentHistoryDataLoader.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
Labels: 버그

#130 Fix: 게시글 - 이미지 조회 leftJoin으로 수정
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
Labels: 버그

#132 Fix: 유저 is_deleted = 0 조건 제거, 일기 남은기간 계산 수정
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/user/domain/User.java
Labels: 수정

#135 Fix: 남은기간 알림 job 등록
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/service/DiaryService.java
  src/main/java/com/palette/infra/fcm/PushNotificationService.java
  src/main/java/com/palette/infra/scheduler/job/HistoryRemindOne.java
  src/main/java/com/palette/infra/scheduler/job/HistoryRemindTwo.java
Labels: 기능

#136 Fix: 알림 히스토리 조회 offset, size 적용
  src/main/java/com/palette/alarmhistory/fetcher/AlarmHistoryFetcher.java
  src/main/java/com/palette/alarmhistory/fetcher/dto/AlarmHistoryPageInput.java
  src/main/java/com/palette/alarmhistory/repository/AlarmHistoryQueryRepository.java
  src/main/resources/application-dev.yml
Labels: 수정

#139 Fix: 알림 히스토리 조회 offset, size 적용
  src/main/resources/schema/alarmhistory.graphql
Labels: 수정

#140 Fix: 로그백 트랜잭션ID(UUID) 추가 (#138)
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/exception/common/GlobalErrorType.java
  src/main/java/com/palette/exception/graphql/DiaryDiscardException.java
  src/main/java/com/palette/filter/TransactionFilter.java
  src/main/resources/logback-spring.xml
Labels: 수정

#145 Fix: Multipart 업로드 예외처리 추가 (#142)
  src/main/java/com/palette/exception/RestExceptionHandler.java
  src/main/java/com/palette/exception/common/GlobalErrorType.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 수정

#146 Fix: 일기장 나가기 알림에 나간여부 data 추가 (#143)
  src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
  src/main/java/com/palette/infra/fcm/PushNotificationService.java
Labels: 수정

#147 Fix: firstResult/maxResults 에러 해결 (#137)
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
Labels: 리팩토링

#148 Fix: 일기 & 히스토리 조회시 page 중복 문제 해결
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
  src/main/java/com/palette/filter/TransactionFilter.java
Labels: 버그

#149 Fix: 일기 홈 조회시 일기장에 나간유저 키값 추가
  src/main/java/com/palette/diary/dataloader/OutedUserDataLoader.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
  src/main/resources/schema/entity.graphql
Labels: 수정

#151 Fix: 일기 홈조회에서 과거 히스토리 조회 리스트 추가
  src/main/java/com/palette/diary/dataloader/JoinUserDataLoader.java
  src/main/java/com/palette/diary/dataloader/OutedUserDataLoader.java
  src/main/java/com/palette/diary/dataloader/PastHistoriesDataLoader.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
  src/main/resources/schema/entity.graphql
Labels: 수정

#152 Fix: 프로필 이미지 로직 수정 및 히스토리 일기 제목 추가
  src/main/java/com/palette/common/UserProfileImgProperties.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/fetcher/dto/SelectHistoryOutput.java
  src/main/java/com/palette/user/fetcher/UserFetcher.java
  src/main/resources/schema/diary.graphqls
Labels: 수정

#153 Fix: 유저탈퇴시 모든 일기장에서 나감 처리
  src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
  src/main/java/com/palette/user/UserController.java
Labels: 수정

#154 Fix: 일기 완성알림 문구 수정
  src/main/java/com/palette/infra/fcm/PushNotificationService.java
Labels: 수정

#155 Fix: 일기 정렬 순서 변경
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
Labels: 수정

#156 Fix: 일기 시작 알림 문구 수정
  src/main/java/com/palette/infra/fcm/PushNotificationService.java
Labels: 수정

#158 Fix: 일기장 정렬 버그 픽스 및 알림 문구 띄어쓰기 추가
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/infra/fcm/PushNotificationService.java
Labels: 수정

#159 Fix: 일기 홈 조회 API response 수정
  src/main/java/com/palette/diary/dataloader/PastHistoriesDataLoader.java
  src/main/java/com/palette/diary/dataloader/dto/PastHistoriesDto.java
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/fetcher/dto/PastHistory.java
  src/main/java/com/palette/diary/repository/query/DiaryQueryRepository.java
  src/main/resources/schema/entity.graphql
Labels: 수정

#160 Fix: 일기 1차, 2차알림 단위 '시간'으로 수정
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/service/DiaryService.java
  src/main/java/com/palette/infra/fcm/PushNotificationService.java
Labels: 수정

#161 Fix: 알림 히스토리 조회 orderby 조건 추가
  src/main/java/com/palette/alarmhistory/repository/AlarmHistoryQueryRepository.java
Labels: 수정

#162 Fix: 히스토리 Graphql 엔티티 고정기간 response 추가
  .github/workflows/build-push-develop.yml
  .github/workflows/build-push-master.yml
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/resources/schema/entity.graphql
Labels: 수정

#163 Fix: periodDays 계산 수정
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
Labels: 수정

#164 Fix: 탈퇴시 일기나감 알림 추가
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/event/PushAlarmEventDto.java
  src/main/java/com/palette/event/PushAlarmEventHandler.java
  src/main/java/com/palette/user/UserController.java
Labels: 수정

#165 Fix: 탈퇴시 일기나감 알림 추가 쿼리조건 수정
  src/main/java/com/palette/diary/repository/DiaryGroupRepository.java
Labels: 수정

#168 Chore: main CI / CD 테스트
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/data_dummy.sql
  src/main/resources/logback-spring.xml
Labels: 설정

#171 Fix: 일기 생성시 초대코드 중복검사 추가
  src/main/java/com/palette/diary/fetcher/DiaryFetcher.java
  src/main/java/com/palette/diary/repository/DiaryRepository.java
Labels: 수정
